version: "3.5"

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
  in_memory_db:
    image: redis:7
    ports:
      - "6379:6379"
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
